### ISSUE TITLE
dev/prod mistake?

### ISSUE THREAD

**Issue by AknEp** [bstaruk/starbase#35]
https://github.com/bstaruk/starbase/blob/master/package.json#L27

It would be changed to this...?

```
    "build": "webpack -p --config ./webpack/webpack.config.prod.js --mode production",
    "watch": "webpack-dev-server --config ./webpack/webpack.config.dev.js --mode development"
```

**Comment by bstaruk** [comment]
Great catch! Can't believe I missed that :)

Thank you for taking the time to report this. I'll have it patched up shortly.
