### ISSUE TITLE
Stylelint warnings from vendor files

### ISSUE THREAD

**Issue by i5ar** [bstaruk/starbase#37]
When running the development server I'd like to exclude the warnings from a vendor file (i.e. `purecss`).
I tried using `.stylelintignore` or using `/* stylelint-disable */` before the `@import` but without success.
What do you suggest?
Thanks!

**Comment by bstaruk** [comment]
On projects where I use vendor libraries that I don't want to lint, I'll put the following line in my `.stylelintrc` just below the `extends` block:

`"ignoreFiles": "node_modules/**/*.css",`

This'd avoid linting anything in your `node_modules` folder, but you can tweak it to only ignore css from specific libraries.

I think this is what you're looking for, but if I'm misunderstanding perhaps you can link to your repo and I can give it a closer look.

**Comment by i5ar** [comment]
That was it, thank you so much.
