### ISSUE TITLE
CSS watch doesn't watch

### ISSUE THREAD

**Issue by orafal-dev** [bstaruk/starbase#38]
Whenever I change something in any `.css` file, dev server doesn't respond to this and says that `[WDS] Nothing changed.` - but in fact I've changed few things across at least 2 files.

**Comment by bstaruk** [comment]
Thanks for reporting this, @rafalolszewski94!

Can you check out the latest version that I just pushed (only contains some dependency updates)?

I was able to reproduce the issue, but it seems to have been resolved by one of the updates... `mini-css-extract-plugin` if I had to guess.

**Comment by bstaruk** [comment]
Closing this issue, as I was able to reproduce the issue before the patch but not after.

If the issue persists, please feel free to re-open it and I'll take a closer look.
