### ISSUE TITLE
Possibility to to make a TS version?

### ISSUE THREAD

**Issue by LockeAG** [bstaruk/starbase#52]
For the sake of science , is there a possibility to make a TS version???

https://medium.com/@francesco.agnoletto/how-to-set-up-typescript-with-babel-and-webpack-6fba1b6e72d5

**Comment by bstaruk** [comment]
Hey @LockeAG! I may one day consider creating a TS port of starbase, but I've got my hands full with the vanilla version, along with [starbase-react](https://github.com/bstaruk/starbase-react), and don't see myself creating another port any time soon.

That being said, if you wanted to fork the project and work on a TS port, I'd be happy to contribute to the project as best I can. Reach out to me via email (listed on my profile) if you'd like to chat more about that.

I'm going to close this issue, as it doesn't really pertain to starbase (vanilla), but I will certainly keep it in mind for the next time I'm looking for a new project!
